version: "3.7"
services:

  # Laravel Service
  laravel:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www:rw
    networks:
      - app-network

  # Nginx Service
  nginx:
    image: nginx:1.21.4-alpine
    restart: unless-stopped
    ports:
      - "${PORT:-8000}:80"
    volumes:
      - ./src/:/var/www
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf
      - ./nginx/error.log:/var/log/nginx/error.log
      - ./nginx/access.log:/var/log/nginx/access.log
    networks:
      - app-network

networks:
  app-network:
    driver: bridge